
#3000 server 1 default
#4000 server 2 without refresh token
#5000 server 1 authServer

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzaGhvb3IiLCJpYXQiOjE2OTY5NDU2MzYsImV4cCI6MTY5Njk0NTY1MX0.hYjFy-qtOqcb0wlRrDsUAWf_ub9T-q5KW46TmN940-Q

###

DELETE http://localhost:5000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzaGhvb3IiLCJpYXQiOjE2OTY5NDU1NTF9.flKoLTEp7RAFmwNCelm5fmoDjvlwO_GjIcyf6NBhfD8"
}

###

POST http://localhost:5000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzaGhvb3IiLCJpYXQiOjE2OTY5NDU1NTF9.flKoLTEp7RAFmwNCelm5fmoDjvlwO_GjIcyf6NBhfD8"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "userName" : "Mashhoor"
}